# Configuración de Servidor
server.port=8080

# Configuración Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/elecciones_unp
spring.datasource.username=postgres
spring.datasource.password=root

# Configuración JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
